name: v2vcflaw

channels:
  - conda-forge
dependencies:
  - python=3.7
  - jupyterlab
  - ipykernel
  - black
  - pytest
  - ipywidgets
  - numpy
  - bokeh
  - pylint
  - pandas
  - ipympl
  - networkx
  - selenium
